# Generated by Django 5.1.2 on 2024-11-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_news_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='para',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
