# Generated by Django 5.1.2 on 2024-11-18 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='heading',
        ),
    ]
