# Generated by Django 5.1.2 on 2024-11-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_head_category_news_heading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
